spring.application.name=card-service
server.port=9005

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.config.import=configserver:http://localhost:8888/

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always